spring:
  datasource:
    url:  jdbc:mysql://${MYSQL_PORT_3306_TCP_ADDR}:3306/hello?useSSL=false
    username: app
    password: app
    driverClassName: com.mysql.jdbc.Driver
  boot:
    admin:
      client:
        enabled: true
        health-url: http://${WEB_HOST}:8090/health
        management-url: http://${WEB_HOST}:8090/
        service-url: http://${WEB_HOST}:8080/
      url: http://${ADMIN_PORT_8888_TCP_ADDR}:8888
  application:
    name: hello_web

management:
  security:
    enabled: false
  contextPath: /
  port: 8090

#security:
#  basic:
#    enabled: false

logging:
  file: logs/web.log
  level:
    jp:
      myazaki: TRACE
