spring:
  datasource:
    url:  jdbc:mysql://192.168.99.100:3306/hello?useSSL=false
    username: app
    password: app
    driverClassName: com.mysql.jdbc.Driver
  boot:
    admin:
      client:
        enabled: true
      url: http://192.168.99.100:8888
  application:
    name: hello_web

management:
  contextPath: /
  port: 8090

logging:
  file: logs/web.log
  level:
    jp:
      co:
        rakuten: TRACE
